[package]
name = "zed_ios"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lib]
name = "zed_ios"
path = "src/zed_ios.rs"
crate-type = ["staticlib", "rlib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
askpass.workspace = true
assets.workspace = true
futures.workspace = true
gpui = { workspace = true, features = ["font-kit"] }
gpui_tokio.workspace = true
http_client.workspace = true
log.workspace = true
paths.workspace = true
release_channel.workspace = true
zlog.workspace = true
remote.workspace = true
reqwest_client.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
settings.workspace = true
smol.workspace = true
sqlez.workspace = true
theme.workspace = true
ui.workspace = true
util.workspace = true

unicode-segmentation = "1.10"
