[package]
name = "zed_ios"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lib]
name = "zed_ios"
path = "src/zed_ios.rs"
crate-type = ["staticlib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
assets.workspace = true
gpui = { workspace = true, features = ["font-kit"] }
log.workspace = true
settings.workspace = true
theme.workspace = true
ui.workspace = true
util.workspace = true

env_logger = "0.11"
